### ISSUE TITLE
Error: Recipient command failed: 550 Invalid email address

### ISSUE THREAD

**Issue by l02162010** [JoeBiellik/pleasenospam#37]
Hi! @JoeBiellik

I have some question.

###  default.json
```json
{
  // App server
  "app": {
    // Listening address
    "host": "0.0.0.0",
    "port": 80,
    // Host options
    "title": "please, no spam",
    "prettyHtml": true,
    "cacheAge": 86400, // Static file cache lifetime
    "keys": [
      "random key here"
    ],
    // Test email options
    "test": {
      "fromAddress": "mailbot",
      "fromName": "Mr Mailbot",
      "subject": "Your test email is here!",
      "message": "Hello World!\n\nNow go try with a real email!"
    },
    // SMTP server for sending test emails
    "smtp": {
      // Contact address
      "host": "localhost",
      "port": 25
    }
  },
  // Mail server
  "mail": {
    // Listening address
    "host": "0.0.0.0",
    "port": 25,
    // SMTP options
    "hostname": "pleasenospam.local",
    "banner": "Hi can I have some mail please?",
    // Accepted recipient address domains
    "domains": [
      "localhost",
      "pleasenospam.local",
      "foodier.site"
    ]
  },
  // RethinkDB server
  "db": {
    // Contact address
    "host": "localhost",
    "port": 28015,
    "database": "pleasenospam"
  }
}
```

###  docker.json
```json
{
  "app": {
    "keys": [
      "random key here"
    ],
    "smtp": {
      "host": "mail"
    }
  },
  "mail": {
    "hostname": "foodier.site",
    "domains": [
      "pleasenospam.email",
      "spamlessmail.org",
      "foodier.site"
    ]
  },
  "db": {
    "host": "db"
  }
}
```

###  dns setting
![dns setting](https://i.imgur.com/UsE3xiV.png)

### I get the wrong
```json
Error: Can't send mail - all recipients were rejected: 550 Invalid email address
app_1   |     at SMTPConnection._formatError (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
app_1   |     at SMTPConnection._actionRCPT (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:1332:28)
app_1   |     at SMTPConnection.<anonymous> (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:1287:30)
app_1   |     at SMTPConnection._processResponse (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
app_1   |     at SMTPConnection._onData (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
app_1   |     at Socket.<anonymous> (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
app_1   |     at Socket.emit (events.js:314:20)
app_1   |     at addChunk (_stream_readable.js:304:12)
app_1   |     at readableAddChunk (_stream_readable.js:280:9)
app_1   |     at Socket.Readable.push (_stream_readable.js:219:10)
app_1   |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
app_1   |   code: 'EENVELOPE',
app_1   |   response: '550 Invalid email address',
app_1   |   responseCode: 550,
app_1   |   command: 'RCPT TO',
app_1   |   rejected: [ 'morning-ox@foodier.site' ],
app_1   |   rejectedErrors: [
app_1   |     Error: Recipient command failed: 550 Invalid email address
app_1   |         at SMTPConnection._formatError (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
app_1   |         at SMTPConnection._actionRCPT (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:1318:24)
app_1   |         at SMTPConnection.<anonymous> (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:1287:30)
app_1   |         at SMTPConnection._processResponse (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
app_1   |         at SMTPConnection._onData (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
app_1   |         at Socket.<anonymous> (/app/node_modules/smtp-connection/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
app_1   |         at Socket.emit (events.js:314:20)
app_1   |         at addChunk (_stream_readable.js:304:12)
app_1   |         at readableAddChunk (_stream_readable.js:280:9)
app_1   |         at Socket.Readable.push (_stream_readable.js:219:10)
app_1   |         at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
app_1   |       code: 'EENVELOPE',
app_1   |       response: '550 Invalid email address',
app_1   |       responseCode: 550,
app_1   |       command: 'RCPT TO',
app_1   |       recipient: 'morning-ox@foodier.site'
app_1   |     }
app_1   |   ]
app_1   | }

```
Sorry, I am silly
Can you tell me where I did wrong ?
Thank you.

**Comment by JoeBiellik** [comment]
Okay so a few things here.

[This is the code](https://github.com/JoeBiellik/pleasenospam/blob/a04545471ed35a13991b36d6108fcf977e85666a/mail-server.js#L14-L21) which is generating that exception which makes me think its a deployment/configuration issue.

You don't include your Docker configuration or setup, are you running the services under Docker at all? Are you running the services from the same host?
You don't need to make any changes to `default.json`, the `docker.json` file overwrites it when running the services under Docker.
In your JSON files you add the domain `foodier.site` but don't remove my domains, which won't work with your server.

If you are running under Docker with the provided setup then try resetting `default.json` and change the domains to only be yours, otherwise let me know more about your deployment.

I'm also getting a different DNS result to your screenshot:
```shellsession
$ dig A mail.foodier.site +short
159.65.131.148
```

For posterity here is the current zone file for `pleasenospam.email`:
```zone
$TTL 1h
@               IN      SOA     ns1.jcbcdn.com. hostmaster.jcbcdn.com. ( 2019010101 1d 2h 4w 1h )
@               IN      NS      ns1.jcbcdn.com.
@               IN      NS      ns2.jcbcdn.net.
@               IN      NS      ns3.jcbcdn.org.
@               IN      NS      ns4.jcbcdn.com.
@               IN      MX  0   @
@               IN      TXT     "v=spf1 mx a ~all"
@               IN      CAA 0   issue "letsencrypt.org"
@               IN      CAA 0   issuewild "letsencrypt.org"
@               IN      A       144.76.69.79
www             IN      CNAME   @
```

**Comment by l02162010** [comment]
I use docker one and it works !
Thank you much.
I very appreciate you !
